name: Run tests
on: push
jobs:
  test:
    name: Install and run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PHP info
        run: |
          php -v
          php -i
          php -m

      - name: Validate composer files
        run: composer validate --strict

      - name: Lint all PHP files
        run: composer run lint

      - name: Get Composer Cache Directory
        id: composer-cache-dir
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-suggest -o

      - name: Run test suite
        run: composer run test

      - name: Run static code analysis
        run: composer run sa