name: Run tests
on: push
jobs:
  test:
    name: Install and run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PHP info
        run: |
          php -v
          php -i
          php -m

      - name: Validate composer files
        run: composer validate

      - name: Lint all PHP files
        run: composer run lint

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.os }}-node-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest --no-ansi

      - name: Run test suite
        run: composer run test

      - name: Run static code analysis
        run: composer run sa